-- MySQL Script generated by MySQL Workbench
-- 03/25/16 14:07:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DBNHibernate
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DBNHibernate
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DBNHibernate` DEFAULT CHARACTER SET utf8 ;
USE `DBNHibernate` ;

-- -----------------------------------------------------
-- Table `DBNHibernate`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBNHibernate`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(254) NOT NULL,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(10) NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `estado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idusuarios_UNIQUE` (`id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;



-- -----------------------------------------------------
-- Table `DBNHibernate`.`telefones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBNHibernate`.`telefones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `numero` VARCHAR(15) NOT NULL,
  `usuarios_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC),
  INDEX `fk_telefones_usuarios_idx` (`usuarios_id` ASC),
  CONSTRAINT `fk_telefones_usuarios`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `DBNHibernate`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `DBNHibernate`.`tipos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBNHibernate`.`tipos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `DBNHibernate`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DBNHibernate`.`produtos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  `nomeprod` VARCHAR(45) NOT NULL,
  `qnt` INT NOT NULL,
  `data` DATE NULL,
  `usuarios_id` INT NOT NULL,
  `tipo_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuarios_id`, `tipo_id`),
  UNIQUE INDEX `idprodutos_UNIQUE` (`id` ASC),
  INDEX `fk_produtos_usuarios1_idx` (`usuarios_id` ASC),
  INDEX `fk_produtos_tipo1_idx` (`tipo_id` ASC),
  CONSTRAINT `fk_produtos_usuarios1`
    FOREIGN KEY (`usuarios_id`)
    REFERENCES `DBNHibernate`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_produtos_tipo1`
    FOREIGN KEY (`tipo_id`)
    REFERENCES `DBNHibernate`.`tipos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;




SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
